# Generated by Django 5.1 on 2024-08-15 13:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_remove_transaction_user_transaction_fromuser_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='fromUser',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='toUser',
        ),
        migrations.AddField(
            model_name='transaction',
            name='isReciever',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='transaction',
            name='source',
            field=models.CharField(default='Unknown', max_length=100),
        ),
        migrations.AddField(
            model_name='transaction',
            name='user',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user', to=settings.AUTH_USER_MODEL),
        ),
    ]
