# Generated by Django 5.1 on 2024-08-16 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_transaction_category_alter_budgetgoal_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetgoal',
            name='last_refreshed',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
    ]
