# Generated by Django 5.1 on 2024-08-16 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_budgetgoal_last_refreshed'),
    ]

    operations = [
        migrations.AddField(
            model_name='budgetgoal',
            name='next_refresh',
            field=models.DateTimeField(null=True),
        ),
    ]
