# Generated by Django 5.1 on 2024-08-16 11:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_budgetgoal_next_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='next_refresh',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 11, 49, 33, 696129, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
