# Generated by Django 5.1 on 2024-08-16 11:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0014_alter_budgetgoal_next_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='next_refresh',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 11, 53, 44, 486848, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
