# Generated by Django 5.1 on 2024-08-16 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0015_alter_budgetgoal_next_refresh'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='next_refresh',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 11, 56, 59, 663528, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='balance',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=20),
        ),
    ]
