# Generated by Django 5.1 on 2024-08-16 15:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0016_alter_budgetgoal_next_refresh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='next_refresh',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 15, 15, 38, 39, 360422, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='FinancialGoal',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('goal_name', models.CharField(max_length=100)),
                ('target_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('current_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('due_date', models.DateField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
