# Generated by Django 5.1 on 2024-08-17 11:04

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0017_alter_budgetgoal_next_refresh_financialgoal'),
    ]

    operations = [
        migrations.AddField(
            model_name='financialgoal',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='budgetgoal',
            name='next_refresh',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 11, 4, 18, 461327, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
