# Generated by Django 5.1 on 2024-08-17 15:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0018_financialgoal_last_updated_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='next_refresh',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 16, 15, 21, 7, 541850, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='financialgoal',
            name='created_at',
            field=models.DateField(auto_now_add=True),
        ),
    ]
