# Generated by Django 5.1 on 2024-08-23 11:39

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0019_alter_budgetgoal_next_refresh_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='budgetgoal',
            name='next_refresh',
            field=models.DateTimeField(default=datetime.datetime(2024, 9, 22, 11, 39, 46, 421590, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.CreateModel(
            name='RecurringTransaction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('description', models.CharField(max_length=255)),
                ('start_date', models.DateField(auto_now_add=True)),
                ('frequency', models.CharField(choices=[('daily', 'Daily'), ('weekly', 'Weekly'), ('monthly', 'Monthly'), ('yearly', 'Yearly')], max_length=50)),
                ('due_date', models.DateField(null=True)),
                ('receive', models.BooleanField(default=False)),
                ('last_transaction', models.DateField(null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='transaction',
            name='recurring',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.recurringtransaction'),
        ),
    ]
